//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMFv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public string FlightId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<System.TimeSpan> Source_time { get; set; }
        public Nullable<System.TimeSpan> Destination_time { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Fare { get; set; }
        public Nullable<int> NumberOfSeatsLeft { get; set; }
        public Nullable<System.DateTime> DateOfFlight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
