//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMFv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string ReviewId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string RatingComment { get; set; }
        public string Id { get; set; }
        public string BookingId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
